# sudo: required

os: linux

language: generic

dist: xenial

services:
  - docker

before_install:
  - docker build -t kshj12/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kshj12/react-test-app npm run test

after_success:
  - docker build -t kshj12/docker-frontend ./frontend
  - docker build -t kshj12/docker-backend ./backend
  - docker build -t kshj12/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push kshj12/docker-frontend
  - docker push kshj12/docker-backend
  - docker push kshj12/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full-stack-app"
  env: "Docker-FullStack-App-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-886078054091
  bucket_path: "docker-full-stack-app"
  on:
    branch: master

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "docker-fullstack-app"
#   env: "DockerFullstackApp-env"
#   bucket_name: elasticbeanstalk-ap-northeast-2-886078054091
#   bucket_path: "docker-fullstack-app"
#   on:
#     branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY